// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";
import { existsSync } from "fs";

// Load .env.local file if it exists (may not exist in CI/CD environments)
if (existsSync(".env.local")) {
  config({ path: ".env.local" });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource: {
    // Use DIRECT_URL for CLI operations (migrations, db pull, etc.)
    url: process.env["DIRECT_URL"],
  },
})